name: Release and Deploy

on:
  workflow_run:
    workflows: ["AClimate v3 Historical Location ETL Pipeline"]
    types:
      - completed

permissions:
  contents: write
  actions: write

jobs:
  # ------- AUTO-RELEASE FROM MAIN -------- #
  auto-release:
    name: Auto Release from Main
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'stage'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine toml
    
    - name: Generate version tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        tag_prefix: v
    
    - name: Update version in pyproject.toml
      run: |
        python -c "
        import toml
        with open('pyproject.toml', 'r') as f:
            data = toml.load(f)
        data['project']['version'] = '${{ steps.tag_version.outputs.new_version }}'
        with open('pyproject.toml', 'w') as f:
            toml.dump(data, f)
        "
    
    - name: Build package
      run: |
        python -m build
    
    - name: Create Release Assets
      run: |
        # Create legacy zip for compatibility
        zip -r releaseETL.zip ./src/*
        
        # Create comprehensive release package
        tar -czf aclimate-v3-etl-${{ steps.tag_version.outputs.new_version }}.tar.gz \
          src/ tests/ README.md pyproject.toml requirements.txt
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: |
          ## 🚀 Release ${{ steps.tag_version.outputs.new_tag }}
          
          ### 📦 Installation
          ```bash
          pip install git+https://github.com/CIAT-DAPA/aclimate_v3_historical_location_etl.git@${{ steps.tag_version.outputs.new_tag }}
          ```
          
          ### 📝 Changes
          ${{ github.event.head_commit.message }}
          
          ### 🔧 Built with
          - Python 3.10+
          - Modern packaging with pyproject.toml
          - Automated testing and quality checks
          
          ---
          **Full Changelog**: https://github.com/CIAT-DAPA/aclimate_v3_historical_location_etl/compare/${{ steps.tag_version.outputs.previous_tag }}...${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false
    
    - name: Upload Python Package Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/aclimate_v3_historical_location_etl-${{ steps.tag_version.outputs.new_version }}.tar.gz
        asset_name: aclimate_v3_historical_location_etl-${{ steps.tag_version.outputs.new_version }}.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload Wheel Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/aclimate_v3_historical_location_etl-${{ steps.tag_version.outputs.new_version }}-py3-none-any.whl
        asset_name: aclimate_v3_historical_location_etl-${{ steps.tag_version.outputs.new_version }}-py3-none-any.whl
        asset_content_type: application/zip
    
    - name: Upload Legacy ETL Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./releaseETL.zip
        asset_name: releaseETL.zip
        asset_content_type: application/zip
    
    - name: Upload Complete Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./aclimate-v3-etl-${{ steps.tag_version.outputs.new_version }}.tar.gz
        asset_name: aclimate-v3-etl-${{ steps.tag_version.outputs.new_version }}.tar.gz
        asset_content_type: application/gzip
    
    - name: Commit version update
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "🔖 Update version to ${{ steps.tag_version.outputs.new_version }}"
        file_pattern: pyproject.toml

  # ------- MANUAL RELEASE FROM TAGS -------- #
  manual-release:
    name: Manual Release from Tag
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Create Release Assets
      run: |
        zip -r releaseETL.zip ./src/*
        
        # Get version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        tar -czf aclimate-v3-etl-${VERSION}.tar.gz \
          src/ tests/ README.md pyproject.toml requirements.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          releaseETL.zip
          aclimate-v3-etl-*.tar.gz
        body: |
          ## 🚀 Manual Release ${{ github.ref_name }}
          
          ### 📦 Installation
          ```bash
          pip install git+https://github.com/CIAT-DAPA/aclimate_v3_historical_location_etl.git@${{ github.ref_name }}
          ```
          
          ### 🔧 Built with
          - Python 3.10+
          - Modern packaging with pyproject.toml
          - Automated testing and quality checks
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Opcional: Publicar en PyPI
    # - name: Publish to PyPI
    #   env:
    #     TWINE_USERNAME: __token__
    #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    #   run: |
    #     python -m twine upload dist/*
